name: Repo Dispatcher
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select code branch to build'
        default: '18.06'
        require: true
      device:
        description: 'select device to build'
        default: 'r2s'
        required: true
      package_clean:
        description: 'check to make clean package'
        default: 'false'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.SEC_TOKEN }}" \
            -d '{"event_type": "${{ github.event.inputs.device }}", "client_payload": {"branch": "${{ github.event.inputs.branch }}", "device": "${{ github.event.inputs.device }}", "package_clean": "${{ github.event.inputs.package_clean }}" }}'
